### ISSUE TITLE
您好，我在红米8 上测试的时候 选择相册图片二维码 识别失败 请教一下是什么原因

### ISSUE THREAD

**Issue by ChengGPBU** [ahuyangdong/QrCodeDemo4#1]
![image](https://user-images.githubusercontent.com/24949641/47780864-44ae1800-dd37-11e8-8884-644d44d5d69e.png)
这个方法 返回null

**Comment by ahuyangdong** [comment]
不好意思才看到，留言没有通知提醒我。是文件路径的问题，近期我已经找到方案替代这个了，关注下最新的代码提交内容

**Comment by ChengGPBU** [comment]
感谢 感谢  我看一下 更新的代码
