### ISSUE TITLE
大佬什么时候更新一下啊

### ISSUE THREAD

**Issue by yutils** [ahuyangdong/QrCodeDemo4#3]
大佬很多类过时了。什么时候更新一下啊。好多人都用你的是的源码。
转到AndroidX，API29之后，一大堆过时警告。虽然不影响使用。但是以后升级到安卓11，安卓12，某些过时类剔除了就跑不起了。

**Comment by yutils** [comment]
3.4.0之后，升到java8之后，低于安卓22版本就跑不起了
implementation 'com.google.zxing:core:3.4.0'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by yutils** [comment]
不好意思  才看到你的这个项目QrCodeLib
我居然造了一个 一模一样的轮子。我自己都服了

**Comment by ahuyangdong** [comment]
> 不好意思 才看到你的这个项目QrCodeLib
> 我居然造了一个 一模一样的轮子。我自己都服了

不错不错，重要的是锻炼，重不重复的无所谓啦。Androidx的事情有时间的话我来瞅瞅吧，谢谢关注。
